sudo: required
language: php
php:
  - "5.6"
  - "7.0"

cache:
  directories:
    - vendor

before_script:
  - composer install
  - sudo chown :travis tests/integration/src/data
  - sudo chmod g+rw tests/integration/src/data

script:
  - mkdir -p build/logs
  - phpunit -c tests/phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
